package analyzer

import (
	"crypto/sha256"
	"fmt"
	"strconv"
	"strings"
	"sync"
)

// Anonymizer provides deterministic, session-consistent data masking for PAN and Track data.
type Anonymizer struct {
	mu       sync.RWMutex
	panMap   map[string]string
	unsecure bool
}

// NewAnonymizer creates a new Anonymizer instance with caching.
func NewAnonymizer(unsecure bool) *Anonymizer {
	return &Anonymizer{
		panMap:   make(map[string]string),
		unsecure: unsecure,
	}
}

var defaultAnonymizer = NewAnonymizer(false)

// AnonymizePAN masks a Primary Account Number (PAN) starting from the 9th position
// with deterministic digits and sets positions 14, 15, 16 to "000" to indicate it is autogenerated.
func (a *Anonymizer) AnonymizePAN(pan string) string {
	if a == nil || a.unsecure {
		return pan
	}
	panClean := strings.TrimSpace(pan)
	length := len(panClean)
	if length < 9 {
		return panClean
	}

	a.mu.RLock()
	cached, ok := a.panMap[panClean]
	a.mu.RUnlock()
	if ok {
		return cached
	}

	a.mu.Lock()
	defer a.mu.Unlock()
	if cached, ok := a.panMap[panClean]; ok {
		return cached
	}

	prefix := panClean[:8]
	var masked string

	if length >= 16 {
		// Positions 9..13 (5 digits): deterministic numbers
		randDigits := deterministicNumericDigits(panClean, 5)
		// Positions 14..16 (3 digits): "000"
		autogenSuffix := "000"
		tail := ""
		if length > 16 {
			tail = panClean[16:]
		}
		masked = prefix + randDigits + autogenSuffix + tail
	} else if length <= 11 {
		randCount := length - 8
		masked = prefix + deterministicNumericDigits(panClean, randCount)
	} else {
		randCount := length - 8 - 3
		masked = prefix + deterministicNumericDigits(panClean, randCount) + "000"
	}

	a.panMap[panClean] = masked
	return masked
}

// AnonymizeTrack2 anonymizes the PAN portion of Track 2 data (DE 35 / DE 55 subfield 57 / EMV Tag 57)
func (a *Anonymizer) AnonymizeTrack2(track2 string) string {
	if a == nil || a.unsecure || track2 == "" {
		return track2
	}
	sepIdx := -1
	for idx, ch := range track2 {
		if ch == '=' || ch == 'D' || ch == 'd' {
			sepIdx = idx
			break
		}
	}

	if sepIdx > 0 {
		panPart := track2[:sepIdx]
		restPart := track2[sepIdx:]
		return a.AnonymizePAN(panPart) + restPart
	}

	if len(track2) >= 12 {
		return a.AnonymizePAN(track2)
	}
	return track2
}

// AnonymizeTrack1 anonymizes the PAN portion of Track 1 data (DE 45)
func (a *Anonymizer) AnonymizeTrack1(track1 string) string {
	if a == nil || a.unsecure || track1 == "" {
		return track1
	}
	startIdx := 0
	if strings.HasPrefix(track1, "%B") || strings.HasPrefix(track1, "%b") {
		startIdx = 2
	} else if strings.HasPrefix(track1, "%") {
		startIdx = 1
	}

	caretIdx := strings.Index(track1[startIdx:], "^")
	if caretIdx > 0 {
		actualCaretIdx := startIdx + caretIdx
		panPart := track1[startIdx:actualCaretIdx]
		restPart := track1[actualCaretIdx:]
		return track1[:startIdx] + a.AnonymizePAN(panPart) + restPart
	}

	return track1
}

// AnonymizeFieldValue anonymizes sensitive field values.
func (a *Anonymizer) AnonymizeFieldValue(fieldID int, val interface{}) interface{} {
	if a == nil || a.unsecure || val == nil {
		return val
	}

	switch v := val.(type) {
	case string:
		switch fieldID {
		case 2:
			return a.AnonymizePAN(v)
		case 35, 55:
			return a.AnonymizeTrack2(v)
		case 45:
			return a.AnonymizeTrack1(v)
		default:
			return v
		}
	case map[string]interface{}:
		res := make(map[string]interface{}, len(v))
		for k, child := range v {
			if k == "57" || strings.EqualFold(k, "track2") || strings.EqualFold(k, "9f6b") {
				if strChild, isStr := child.(string); isStr {
					res[k] = a.AnonymizeTrack2(strChild)
				} else {
					res[k] = a.AnonymizeFieldValue(0, child)
				}
			} else if k == "2" || strings.EqualFold(k, "pan") {
				if strChild, isStr := child.(string); isStr {
					res[k] = a.AnonymizePAN(strChild)
				} else {
					res[k] = a.AnonymizeFieldValue(2, child)
				}
			} else {
				res[k] = a.AnonymizeFieldValue(0, child)
			}
		}
		return res
	default:
		return val
	}
}

// AnonymizePAN masks a Primary Account Number using default deterministic anonymizer.
func AnonymizePAN(pan string) string {
	return defaultAnonymizer.AnonymizePAN(pan)
}

// AnonymizeTrack2 masks Track 2 data using default deterministic anonymizer.
func AnonymizeTrack2(track2 string) string {
	return defaultAnonymizer.AnonymizeTrack2(track2)
}

// AnonymizeTrack1 masks Track 1 data using default deterministic anonymizer.
func AnonymizeTrack1(track1 string) string {
	return defaultAnonymizer.AnonymizeTrack1(track1)
}

// AnonymizeFieldValue anonymizes sensitive field values using default deterministic anonymizer.
func AnonymizeFieldValue(fieldID int, val interface{}, unsecure bool) interface{} {
	if unsecure {
		return val
	}
	return defaultAnonymizer.AnonymizeFieldValue(fieldID, val)
}

func deterministicNumericDigits(seed string, n int) string {
	if n <= 0 {
		return ""
	}
	h := sha256.Sum256([]byte(seed))
	var sb strings.Builder
	for i := 0; i < n; i++ {
		b := h[i%len(h)]
		sb.WriteString(strconv.Itoa(int(b % 10)))
	}
	return sb.String()
}

// FormatProcCode formats a Processing Code to 6 characters zero-padded (e.g. "0" -> "000000", "200000" -> "200000").
func FormatProcCode(de3 string) string {
	trimmed := strings.TrimSpace(de3)
	if trimmed == "" {
		return ""
	}
	if len(trimmed) >= 6 {
		return trimmed
	}
	if _, err := strconv.Atoi(trimmed); err == nil {
		return fmt.Sprintf("%06s", trimmed)
	}
	return trimmed
}
