package analyzer

import (
	"crypto/rand"
	"fmt"
	"math/big"
	"strings"
)

// AnonymizePAN masks a Primary Account Number (PAN) starting from the 9th position
// with random numeric digits and sets positions 14, 15, 16 to "000" to indicate it is autogenerated.
func AnonymizePAN(pan string) string {
	panClean := strings.TrimSpace(pan)
	length := len(panClean)
	if length < 9 {
		return panClean
	}

	// Keep first 8 digits (BIN)
	prefix := panClean[:8]

	if length >= 16 {
		// Positions 9..13 (5 digits): random numbers
		randDigits := randomNumericDigits(5)
		// Positions 14..16 (3 digits): "000"
		autogenSuffix := "000"
		// Positions 17+ (if any)
		tail := ""
		if length > 16 {
			tail = panClean[16:]
		}
		return prefix + randDigits + autogenSuffix + tail
	}

	// For lengths between 9 and 15:
	if length <= 11 {
		randCount := length - 8
		return prefix + randomNumericDigits(randCount)
	}

	randCount := length - 8 - 3
	return prefix + randomNumericDigits(randCount) + "000"
}

func randomNumericDigits(n int) string {
	if n <= 0 {
		return ""
	}
	var sb strings.Builder
	for i := 0; i < n; i++ {
		num, err := rand.Int(rand.Reader, big.NewInt(10))
		if err != nil {
			sb.WriteString("5")
		} else {
			sb.WriteString(fmt.Sprintf("%d", num.Int64()))
		}
	}
	return sb.String()
}

// AnonymizeTrack2 anonymizes the PAN portion of Track 2 data (DE 35 / DE 55 subfield 57 / EMV Tag 57)
func AnonymizeTrack2(track2 string) string {
	if track2 == "" {
		return ""
	}
	// Look for '=' or 'D' or 'd' separator
	sepIdx := -1
	for idx, ch := range track2 {
		if ch == '=' || ch == 'D' || ch == 'd' {
			sepIdx = idx
			break
		}
	}

	if sepIdx > 0 {
		panPart := track2[:sepIdx]
		restPart := track2[sepIdx:]
		return AnonymizePAN(panPart) + restPart
	}

	if len(track2) >= 12 {
		return AnonymizePAN(track2)
	}
	return track2
}

// AnonymizeTrack1 anonymizes the PAN portion of Track 1 data (DE 45)
func AnonymizeTrack1(track1 string) string {
	if track1 == "" {
		return ""
	}
	startIdx := 0
	if strings.HasPrefix(track1, "%B") || strings.HasPrefix(track1, "%b") {
		startIdx = 2
	} else if strings.HasPrefix(track1, "%") {
		startIdx = 1
	}

	caretIdx := strings.Index(track1[startIdx:], "^")
	if caretIdx > 0 {
		actualCaretIdx := startIdx + caretIdx
		panPart := track1[startIdx:actualCaretIdx]
		restPart := track1[actualCaretIdx:]
		return track1[:startIdx] + AnonymizePAN(panPart) + restPart
	}

	return track1
}

// AnonymizeFieldValue anonymizes sensitive field values if unsecure is false.
func AnonymizeFieldValue(fieldID int, val interface{}, unsecure bool) interface{} {
	if unsecure || val == nil {
		return val
	}

	switch v := val.(type) {
	case string:
		switch fieldID {
		case 2:
			return AnonymizePAN(v)
		case 35, 55:
			return AnonymizeTrack2(v)
		case 45:
			return AnonymizeTrack1(v)
		default:
			return v
		}
	case map[string]interface{}:
		res := make(map[string]interface{}, len(v))
		for k, child := range v {
			if k == "57" || strings.EqualFold(k, "track2") || strings.EqualFold(k, "9f6b") {
				if strChild, isStr := child.(string); isStr {
					res[k] = AnonymizeTrack2(strChild)
				} else {
					res[k] = AnonymizeFieldValue(0, child, unsecure)
				}
			} else if k == "2" || strings.EqualFold(k, "pan") {
				if strChild, isStr := child.(string); isStr {
					res[k] = AnonymizePAN(strChild)
				} else {
					res[k] = AnonymizeFieldValue(2, child, unsecure)
				}
			} else {
				res[k] = AnonymizeFieldValue(0, child, unsecure)
			}
		}
		return res
	default:
		return val
	}
}
