// root_inspector.go builds the §C InspectorState from the app's tx
// definitions WITHOUT a live connection and owns the open/pop transitions.
//
// Compose-without-send boundary (honest note): the state is built on the
// exact path `jiso inspect` uses — Repository.Info (declared fields) →
// Repository.Compose (dataset/session interpolation; the composed sample
// message, never sent) → app.NewInfoViewFromComposedMessage (pack + hex
// dump) — so what the inspector shows is the same composition the headless
// CLI prints. Auto values (STAN/RRN/TS) are generated by Compose itself;
// the auto-preview pool is derived deterministically from the composed
// value (counter increments), so `r` cycles without recomputation.
// The live send (SCR-504) lands via TxSendMsg → the §D exchange view;
// "compose-with-dataset on Enter" stays a later ticket, so TxComposeMsg
// remains a logged no-op.
package tui

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"sort"
	"strconv"
	"strings"

	"github.com/moov-io/iso8583"
	"github.com/moov-io/iso8583/field"

	app "jiso/internal/app"
	"jiso/internal/tui/pages"
	"jiso/internal/utils"
)

// openInspector builds the snapshot for tx id and pushes the canonical
// inspector instance (TxDetailMsg from the §B page; the same instance
// backs hotkey 3, so state survives jumps).
func (m *RootModel) openInspector(id string) {
	m.inspector.SetState(m.inspectorStateFor(id))
	m.Push(m.inspector)
}

// inspectorStateFor derives the §C snapshot for tx id. Without an app or
// repository (tests, pre-wire) the result is the empty state — the page
// renders dashes, not zeros.
func (m *RootModel) inspectorStateFor(id string) pages.InspectorState {
	st := pages.InspectorState{TxID: id, MsgIndex: 1, MsgTotal: 1}
	if m.app == nil || id == "" {
		st.TxName = id

		return st
	}
	repo := m.app.Transactions()
	if repo == nil {
		st.TxName = id

		return st
	}

	info, err := repo.Info(id)
	if err != nil || info.Name == "" {
		info.Name = id
	}
	txName, desc, fieldsJSON := info.Name, info.Description, info.FieldsJSON
	st.TxName = txName
	declared := declaredFields(fieldsJSON)

	msg, cerr := repo.Compose(txName)
	if cerr != nil {
		m.fillInspectorComposeError(&st, txName, desc, fieldsJSON, cerr)

		return st
	}

	m.fillInspectorFromComposed(&st, txName, desc, fieldsJSON, msg, declared)

	return st
}

// fillInspectorComposeError renders the info view for a transaction whose
// composition failed.
func (m *RootModel) fillInspectorComposeError(st *pages.InspectorState, txName, desc, fieldsJSON string, cerr error) {
	view := app.NewInfoView(txName, desc, fieldsJSON)
	view.SetComposeError(cerr)
	st.Validation = append(st.Validation, pages.ValidationRow{Text: cerr.Error()})
	maskViewSensitive(view, nil)
	st.RawJSON = marshalJSON(view)
}

// fillInspectorFromComposed renders the inspector state from a composed message:
// raw JSON, pack/pack-render errors, packed hex/describe and field rows.
func (m *RootModel) fillInspectorFromComposed(st *pages.InspectorState, txName, desc, fieldsJSON string, msg *iso8583.Message, declared map[string]string) {
	view := app.NewInfoViewFromComposedMessage(txName, desc, fieldsJSON, msg)
	maskViewSensitive(view, msg)
	st.RawJSON = marshalJSON(view)
	if view.PackError != "" {
		st.Fields = fieldRows(msg, declared)
		st.Validation = append(st.Validation, pages.ValidationRow{Text: view.PackError})
		attachErrors(st.Fields, st.Validation)

		return
	}

	packed, perr := msg.Pack()
	if perr != nil {
		st.Validation = append(st.Validation, pages.ValidationRow{Text: perr.Error()})

		return
	}

	st.HeaderNote = m.headerNote(len(packed))
	st.PackedHex = hexLines(packed)
	// UAT: the fields tab shows the Describe output and the hex pane
	// the standard hexdump (offset, 16 byte pairs, ASCII gutter).
	st.DescribeText = describeTextLines(msg)
	st.PackedDump = utils.StandardHexDump(packed)
	st.Fields = fieldRows(msg, declared)
	st.Validation = append(st.Validation, validateRows(msg, st.Fields)...)
	attachErrors(st.Fields, st.Validation)
}

// describeTextLines renders the utils.Describe output of the composed
// message (the canonical Describe masking via DefaultFilters), one
// state line per Describe output line.
func describeTextLines(msg *iso8583.Message) []string {
	var buf bytes.Buffer
	if err := utils.Describe(msg, &buf); err != nil {
		// Partial output still describes what unpacked; keep it.
		out := strings.Split(strings.TrimRight(buf.String(), "\n"), "\n")
		if len(out) == 1 && out[0] == "" {
			return nil
		}

		return out
	}

	return strings.Split(strings.TrimRight(buf.String(), "\n"), "\n")
}

// headerNote pre-formats the packed pane's header line (wireframe:
// "len hdr: binary2 (0x0079)" — that hex is the message length; we show
// the truth for any header type: header name plus packed byte count).
func (m *RootModel) headerNote(n int) string {
	hdr := ""
	if m.app != nil {
		if cfg := m.app.Config(); cfg != nil {
			hdr = cfg.GetHeader()
		}
	}

	return "len hdr: " + hdr + " - msg " + strconv.Itoa(n) + " bytes"
}

// hexLines pre-wraps the packed bytes into 16-byte lowercase hex lines;
// the page regroups them for the [h] toggle (pure display).
func hexLines(packed []byte) []string {
	digits := hex.EncodeToString(packed)
	const per = 16 * 2
	out := make([]string, 0, (len(digits)+per-1)/per)
	for i := 0; i < len(digits); i += per {
		out = append(out, digits[i:min(i+per, len(digits))])
	}

	return out
}

// declaredFields parses the template field map from Repository.Info's
// fields JSON document (raw placeholder values included).
func declaredFields(fieldsJSON string) map[string]string {
	var raw map[string]any
	if err := json.Unmarshal([]byte(fieldsJSON), &raw); err != nil {
		return nil
	}
	out := make(map[string]string, len(raw))
	for k, v := range raw {
		out[k] = templateValue(v)
	}

	return out
}

// fieldRows walks the composed message's set fields (sorted by number),
// attaching template provenance (Auto/RawPreview), PAN masking, and the
// composite subfield tree.
func fieldRows(msg *iso8583.Message, declared map[string]string) []pages.FieldRow {
	fields := msg.GetFields()
	nums := make([]int, 0, len(fields))
	for n := range fields {
		nums = append(nums, n)
	}
	sort.Ints(nums)

	rows := make([]pages.FieldRow, 0, len(nums))
	for _, n := range nums {
		num := strconv.Itoa(n)
		rows = append(rows, fieldRow(n, fields[n], declared[num], 0))
	}

	return rows
}

// fieldTreeDepth is the composite recursion cap (defensive: malformed
// specs must not hang the frontend).
const fieldTreeDepth = 4

// attachErrors copies validation failures onto the field row whose
// number the error text names ("required field 2 (...) is missing"),
// so the page can red-line that row with the error symbol.
func attachErrors(rows []pages.FieldRow, validation []pages.ValidationRow) {
	for _, v := range validation {
		if v.OK {
			continue
		}
		n := fieldNumMentioned(v.Text)
		attachErrorAt(rows, n, v.Text)
	}
}

// validateRows runs the shared pre-send validation (the same
// app.ValidateMessage the send path uses) without sending, plus the
// composite subfield check: a successful Pack of composite fields
// proves their subfield lengths sum, so the line appears only when the
// message actually carries composites.
func validateRows(msg *iso8583.Message, rows []pages.FieldRow) []pages.ValidationRow {
	out := make([]pages.ValidationRow, 0, 2)
	if err := app.ValidateMessage(msg); err != nil {
		return append(out, pages.ValidationRow{Text: err.Error()})
	}
	out = append(out, pages.ValidationRow{Text: "ok", OK: true})
	if hasComposites(rows) {
		out = append(out, pages.ValidationRow{Text: "subfield lengths sum", OK: true})
	}

	return out
}

// hasComposites reports whether any rendered row carries children.
func hasComposites(rows []pages.FieldRow) bool {
	for _, r := range rows {
		if len(r.Children) > 0 || hasComposites(r.Children) {
			return true
		}
	}

	return false
}

// maskViewSensitive masks PAN-family values inside the view's parsed/
// display surfaces — the declared Fields entries (moov default-filter
// numbers, string values) and the described ParsedMessage (the extended
// isPANField set via the shared maskPAN) — before the JSON crosses to
// the §C raw json tab. PackedHEX stays raw BY DESIGN: it is the wire
// dump, identical to `jiso inspect --json` (the tool's purpose).
func maskViewSensitive(view *app.InfoView, msg *iso8583.Message) {
	if view == nil {
		return
	}
	for key, v := range view.Fields {
		n, err := strconv.Atoi(key)
		if err != nil || !sensitiveFieldNums[n] {
			continue
		}
		if s, ok := v.(string); ok && s != "" {
			view.Fields[key] = maskPAN(s)
		}
	}
	if view.ParsedMessage == "" || msg == nil {
		return
	}
	filters := sensitiveDescribeFilters(msg)
	if len(filters) == 0 {
		return // nothing sensitive in the message: raw IS the truth
	}
	var buf bytes.Buffer
	if err := utils.Describe(msg, &buf, filters...); err != nil {
		return // keep the app-rendered text; nothing better exists
	}
	view.ParsedMessage = buf.String()
}

// sensitiveDescribeFilters re-describes msg's sensitive fields with the
// shared maskPAN, leaving every other field's describe text untouched
// (utils.Describe applies filters only to the fields they name).
func sensitiveDescribeFilters(msg *iso8583.Message) []utils.FieldFilter {
	var out []utils.FieldFilter
	for n, f := range msg.GetFields() {
		if !isPANField(n, fieldName(f)) {
			continue
		}
		out = append(out, utils.FilterField(strconv.Itoa(n),
			func(in string, _ field.Field) string { return maskPAN(in) }))
	}

	return out
}

// marshalJSON serializes the (already masked) inspect view for the raw
// json tab; the packed_hex entry is the raw wire dump by design.
func marshalJSON(view *app.InfoView) string {
	b, err := json.MarshalIndent(view, "", "  ")
	if err != nil {
		return ""
	}

	return string(b)
}
