package pages

import (
	"strings"
	"testing"

	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/charmbracelet/colorprofile"

	"jiso/internal/tui/frame"
)

// trueColorProfile is the colored-golden profile helper.
func trueColorProfile() colorprofile.Profile { return colorprofile.TrueColor }

// TestInspectorTabCycleForward: PaneFocusMsg walks fields → bitmap →
// packed → raw json and wraps (unknown tabs impossible).
func TestInspectorTabCycleForward(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 120, 32)

	want := []int{viewBitmap, viewPacked, viewRawJSON, viewFields}
	for i, w := range want {
		_, _ = in.Update(PaneFocusMsg{})
		if in.Tab() != w {
			t.Fatalf("step %d: tab = %d, want %d", i, in.Tab(), w)
		}
	}
}

// TestInspectorTabCycleBackward: shift+Tab (Reverse) walks backwards
// and wraps.
func TestInspectorTabCycleBackward(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 120, 32)

	want := []int{viewRawJSON, viewPacked, viewBitmap, viewFields}
	for i, w := range want {
		_, _ = in.Update(PaneFocusMsg{Reverse: true})
		if in.Tab() != w {
			t.Fatalf("step %d: tab = %d, want %d", i, in.Tab(), w)
		}
	}
}

// TestInspectorViewMarkers: every tab renders its pane marker line.
func TestInspectorViewMarkers(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 120, 32)

	for _, c := range []struct {
		tab  int
		want string
	}{
		{viewFields, "FIELDS (interpolated"},
		{viewBitmap, "bitmap: [x] set"},
		{viewPacked, "len hdr: binary2"},
		{viewRawJSON, `"mti": "0200"`},
	} {
		inspToTab(t, in, c.tab)
		body := strings.Join(inspBody(t, in), "\n")
		if !strings.Contains(body, c.want) {
			t.Errorf("tab %d lacks %q:\n%s", c.tab, c.want, body)
		}
	}
}

// TestInspectorBreadcrumb: ascii renders "Transactions > Purchase" and
// the Messages(1/12) position.
func TestInspectorBreadcrumb(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 120, 32)

	body := strings.Join(inspBody(t, in), "\n")
	for _, want := range []string{"Transactions > Purchase", "Messages(1/12)"} {
		if !strings.Contains(body, want) {
			t.Errorf("body lacks %q:\n%s", want, body)
		}
	}
}

// TestInspectorCompositeExpandCollapse: right expands 55 (child visible,
// indented), right again on the child expands the nested depth, left
// collapses; enter toggles too.
func TestInspectorCompositeExpandCollapse(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspTreePurchase(), 120, 32)

	cursorOn(t, in, "55")
	_, _ = in.Update(specialKey(tea.KeyRight))
	if !in.IsExpanded("55") {
		t.Fatal("right must expand 55")
	}
	body := strings.Join(inspBody(t, in), "\n")
	if !strings.Contains(body, "Terminal caps") {
		t.Fatalf("expanded 55 lacks child:\n%s", body)
	}

	cursorOn(t, in, "95")
	_, _ = in.Update(specialKey(tea.KeyRight))
	if !in.IsExpanded("55/95") {
		t.Fatal("right must expand 55/95")
	}
	body = strings.Join(inspBody(t, in), "\n")
	if !strings.Contains(body, "Nested") {
		t.Fatalf("nested depth lacks grandchild:\n%s", body)
	}
	if !strings.Contains(body, "    Nested") {
		t.Errorf("grandchild must carry depth indent:\n%s", body)
	}

	_, _ = in.Update(specialKey(tea.KeyLeft))
	if in.IsExpanded("55/95") {
		t.Fatal("left must collapse 55/95")
	}

	// Enter on an expanded composite collapses it (toggle).
	in2 := inspPage(t, inspTreePurchase(), 120, 32)
	cursorOn(t, in2, "55")
	_, _ = in2.Update(enterKey())
	if !in2.IsExpanded("55") {
		t.Fatal("enter must expand a composite")
	}
	_, _ = in2.Update(enterKey())
	if in2.IsExpanded("55") {
		t.Fatal("enter must collapse an expanded composite")
	}
}

// TestInspectorEnterYieldsCompose: Enter on a leaf yields
// TxComposeMsg{ID}; Enter on a composite only expands (nil cmd); Enter
// on the empty inspector yields nothing.
func TestInspectorEnterYieldsCompose(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspTreePurchase(), 120, 32)

	cursorOn(t, in, "3")
	_, cmd := in.Update(enterKey())
	if cmd == nil {
		t.Fatal("enter on leaf must yield a cmd")
	}
	if got, ok := cmd().(TxComposeMsg); !ok || got.ID != "Purchase" {
		t.Errorf("enter dispatched %#v, want TxComposeMsg{Purchase}", cmd())
	}

	in2 := inspPage(t, InspectorState{}, 120, 32)
	_, cmd = in2.Update(press('\r'))
	if cmd != nil {
		t.Errorf("enter on empty inspector ran %#v, want nil", cmd())
	}
}

// TestInspectorPoolCyclesWraps: r advances the auto-preview pool and
// wraps modulo the pool size (values pre-generated by root; the page
// only moves an index).
func TestInspectorPoolCyclesWraps(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspTreePurchase(), 160, 32)

	body := strings.Join(inspBody(t, in), "\n")
	if !strings.Contains(body, "0906120411") {
		t.Fatalf("initial auto preview missing:\n%s", body)
	}
	_, _ = in.Update(press('r'))
	body = strings.Join(inspBody(t, in), "\n")
	if !strings.Contains(body, "0906120511") {
		t.Fatalf("r must show pool[1]:\n%s", body)
	}
	_, _ = in.Update(press('r'))
	_, _ = in.Update(press('r'))
	if in.PoolIndex() != 3 {
		t.Fatalf("pool index = %d, want 3", in.PoolIndex())
	}
	body = strings.Join(inspBody(t, in), "\n")
	if !strings.Contains(body, "0906120411") {
		t.Errorf("pool must wrap to [0]:\n%s", body)
	}
}

// TestInspectorPackedStandardDump pins the UAT contract: the packed
// pane renders the standard hexdump (offset, 16 byte pairs, ASCII
// gutter) and there is no h grouping toggle anymore.
func TestInspectorPackedStandardDump(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 120, 32)
	inspToTab(t, in, viewPacked)

	body := strings.Join(inspBody(t, in), "\n")
	if !strings.Contains(body, "00000000  00 79 32 30 30 00 30 00") {
		t.Errorf("packed pane missing the standard hexdump line:\n%s", body)
	}
	if !strings.Contains(body, "|.y200.0.0.0.20.2|") {
		t.Errorf("packed pane missing the ASCII gutter:\n%s", body)
	}
	if strings.Contains(body, "bytes/line") {
		t.Errorf("grouping hint must be gone:\n%s", body)
	}

	before := body
	_, _ = in.Update(press('h'))
	if strings.Join(inspBody(t, in), "\n") != before {
		t.Error("h must not change the packed pane (toggle removed)")
	}
}

// TestInspectorFieldsDescribeView pins the UAT contract: with root's
// Describe output present, the fields tab renders those lines.
func TestInspectorFieldsDescribeView(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 140, 32)
	body := strings.Join(inspBody(t, in), "\n")
	for _, want := range []string{"ISO8583 Message:", "MTI", "F2   Primary Account Number", "4567****3456"} {
		if !strings.Contains(body, want) {
			t.Errorf("fields view missing %q:\n%s", want, body)
		}
	}
	if strings.Contains(body, "Proc Code") {
		t.Error("tree rows must not render while the Describe output is present")
	}
}

// TestInspectorJKClampsExpanded: with the tree expanded, j clamps at
// the last visible row and k at the first.
func TestInspectorJKClampsExpanded(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspTreePurchase(), 120, 32)
	cursorOn(t, in, "55")
	_, _ = in.Update(specialKey(tea.KeyRight))
	cursorOn(t, in, "95")
	_, _ = in.Update(specialKey(tea.KeyRight))
	cursorOn(t, in, "01")

	for range 30 {
		_, _ = in.Update(press('j'))
	}
	rows := len(in.visibleRows())
	if in.Cursor() != rows-1 {
		t.Fatalf("cursor = %d, want clamp at %d", in.Cursor(), rows-1)
	}
	for range 30 {
		_, _ = in.Update(press('k'))
	}
	if in.Cursor() != 0 {
		t.Fatalf("cursor = %d, want clamp at 0", in.Cursor())
	}
}

// TestInspectorValidationSymbols: ok rows carry the ok symbol and
// failed rows the error symbol (never colour alone).
func TestInspectorValidationSymbols(t *testing.T) {
	t.Parallel()

	asciiOK := inspPage(t, inspPurchase(), 120, 32)
	body := strings.Join(inspBody(t, asciiOK), "\n")
	if !strings.Contains(body, "[ok] ok") {
		t.Errorf("ascii ok line lacks [ok]:\n%s", body)
	}

	asciiErr := inspPage(t, inspBroken(), 120, 32)
	body = strings.Join(inspBody(t, asciiErr), "\n")
	if !strings.Contains(body, "[x] field 3 (Processing Code)") {
		t.Errorf("ascii error row lacks the error symbol:\n%s", body)
	}

	color := NewInspector(testTheme(t, trueColorProfile()))
	color.SetState(inspBroken())
	_, _ = color.Update(windowSize(120, 32))
	cbody := color.View().Content
	if !strings.Contains(cbody, "✗") {
		t.Errorf("truecolor error row lacks ✗:\n%s", cbody)
	}
}

// TestInspectorMaskedDisplay: the page shows root's pre-masked PAN
// (• truecolor, * ascii) with the (masked) tag and never a raw PAN.
func TestInspectorMaskedDisplay(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspTreePurchase(), 160, 32)
	body := strings.Join(inspBody(t, in), "\n")
	if !strings.Contains(body, "4567********3456") || !strings.Contains(body, "(masked)") {
		t.Errorf("ascii masked display wrong:\n%s", body)
	}
	if strings.Contains(body, "4567890123456789") {
		t.Errorf("raw PAN leaked:\n%s", body)
	}

	color := NewInspector(testTheme(t, trueColorProfile()))
	color.SetState(inspTreePurchase())
	_, _ = color.Update(windowSize(160, 32))
	if !strings.Contains(color.View().Content, "4567••••••••3456") {
		t.Errorf("truecolor masked display wrong:\n%s", color.View().Content)
	}
}

// TestInspectorBitmapSetBits: the grid marks exactly the set top-level
// fields; field 0 (MTI) is not a bit; field 70 implies the extension
// bit 1 and a second 64-bit block.
func TestInspectorBitmapSetBits(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 120, 32)
	inspToTab(t, in, viewBitmap)
	body := strings.Join(inspBody(t, in), "\n")

	for _, want := range []string{"02[x]", "03[x]", "07[x]", "11[x]", "55[x]", "70[x]", "01[x]"} {
		if !strings.Contains(body, want) {
			t.Errorf("bitmap lacks set-bit cell %s:\n%s", want, body)
		}
	}
	for _, no := range []string{"04[x]", "05[x]", "12[x]", "66[x]"} {
		if strings.Contains(body, no) {
			t.Errorf("bitmap marks clear bit %s:\n%s", no, body)
		}
	}
	if !strings.Contains(body, "121-") {
		t.Errorf("field 70 must extend the grid to 128 bits:\n%s", body)
	}
}

// TestInspectorRawJSONPassthrough: the raw json tab shows the root-
// serialized JSON verbatim.
func TestInspectorRawJSONPassthrough(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 120, 32)
	inspToTab(t, in, viewRawJSON)
	lines := inspBody(t, in)
	joined := strings.Join(lines, "\n")
	for _, want := range []string{`"name": "Purchase",`, `"mti": "0200"`, `}`} {
		if !strings.Contains(joined, want) {
			t.Errorf("raw json lacks %q:\n%s", want, joined)
		}
	}
}

// TestInspectorEmptyDashes: an empty InspectorState renders dashes,
// never zeros, and names the next action.
func TestInspectorEmptyDashes(t *testing.T) {
	t.Parallel()

	in := inspPage(t, InspectorState{}, 120, 32)
	body := strings.Join(inspBody(t, in), "\n")
	if !strings.Contains(body, "Messages(-/-)") {
		t.Errorf("empty Messages counter must dash:\n%s", body)
	}
	if strings.Contains(body, "Messages(0/0)") {
		t.Errorf("zero counters leaked:\n%s", body)
	}
	if !strings.Contains(body, "Select a transaction first.") || !strings.Contains(body, "Transactions > -") {
		t.Errorf("empty body lacks the next-action hint:\n%s", body)
	}
	for _, tab := range []int{viewBitmap, viewPacked, viewRawJSON} {
		inspToTab(t, in, tab)
		if !strings.Contains(strings.Join(inspBody(t, in), "\n"), "-") {
			t.Errorf("tab %d body must dash on empty", tab)
		}
	}
}

// TestInspectorWidthsNoOverflow: at 120/90/70 wide terminals every
// body line stays inside the content area and the body is exactly the
// content height on all four tabs.
func TestInspectorWidthsNoOverflow(t *testing.T) {
	t.Parallel()

	for _, w := range []int{120, 90, 70} {
		for _, tab := range []int{viewFields, viewBitmap, viewPacked, viewRawJSON} {
			in := inspPage(t, inspTreePurchase(), w, 30)
			cursorOn(t, in, "55")
			_, _ = in.Update(specialKey(tea.KeyRight))
			inspToTab(t, in, tab)

			_, ch := frame.ContentSize(w, 30)
			lines := strings.Split(in.View().Content, "\n")
			if len(lines) != ch {
				t.Fatalf("w=%d tab=%d: body %d lines, want %d", w, tab, len(lines), ch)
			}
			for i, ln := range lines {
				if n := cellWidth(ln); n > w {
					t.Fatalf("w=%d tab=%d line %d: %d cells > %d", w, tab, i, n, w)
				}
			}
		}
	}
}

// TestInspectorHintsAreWired: the §C hints name the page-local keys and
// keep tab/compose/back primary for the narrow footer.
func TestInspectorHintsAreWired(t *testing.T) {
	t.Parallel()

	in := NewInspector(asciiTheme(t))

	prim := map[string]bool{}
	all := map[string]bool{}
	for _, h := range in.Hints() {
		all[h.Key] = true
		if h.Primary {
			prim[h.Key] = true
		}
	}
	for _, k := range []string{"tab", "enter", "esc"} {
		if !prim[k] {
			t.Errorf("hint %s must be primary", k)
		}
	}
	for _, k := range []string{"j/k", "r"} {
		if !all[k] {
			t.Errorf("hint %s missing", k)
		}
	}
}

// TestInspectorSetStateKeepsInteraction: a re-pushed snapshot keeps the
// tab and clamps the cursor into the new tree.
func TestInspectorSetStateKeepsInteraction(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 120, 32)
	inspToTab(t, in, viewPacked)
	for range 10 {
		_, _ = in.Update(press('j'))
	}

	in.SetState(InspectorState{TxID: "X", TxName: "X"})
	if in.Tab() != viewPacked {
		t.Fatalf("SetState reset the tab to %d", in.Tab())
	}
	if in.Cursor() != 0 {
		t.Fatalf("cursor = %d, want clamped to 0", in.Cursor())
	}
}

// TestInspectorUnknownKeysIgnored: unbound keys change nothing.
func TestInspectorUnknownKeysIgnored(t *testing.T) {
	t.Parallel()

	in := inspPage(t, inspPurchase(), 120, 32)
	_, cmd := in.Update(press('z'))
	if cmd != nil {
		t.Fatalf("unknown key ran a cmd")
	}
}

// specialKey builds a named key press (arrows/enter) for page tests
// (Text stays empty: bubbles matches "enter" only on the bare code).
func specialKey(code rune) tea.KeyPressMsg { return tea.KeyPressMsg{Code: code} }

// enterKey is the Enter press as the terminal delivers it.
func enterKey() tea.KeyPressMsg { return specialKey('\r') }

// cellWidth is the printable cell width of a rendered line.
func cellWidth(s string) int { return lipgloss.Width(s) }
