// inspector_tree.go holds the fields-tree bookkeeping: flattening the
// FieldRow tree into visible rows honouring the expand set, cursor
// movement with clamps, composite expand/collapse, and the display-value
// resolution for auto-preview and masked rows (pure string work — the
// values themselves were pre-generated by root).
package pages

import (
	"strconv"
	"strings"

	tea "charm.land/bubbletea/v2"
)

// visRow is one flattened visible row of the fields tree.
type visRow struct {
	row       FieldRow
	path      string // Num path, e.g. "55/95"
	depth     int
	composite bool
	expanded  bool
}

// visibleRows flattens Fields in order: a composite row is followed by
// its children only while its path is in the expand set.
func (in *Inspector) visibleRows() []visRow {
	out := make([]visRow, 0, len(in.state.Fields))
	var walk func(rows []FieldRow, depth int, prefix string)
	walk = func(rows []FieldRow, depth int, prefix string) {
		for _, r := range rows {
			path := r.Num
			if prefix != "" {
				path = prefix + "/" + r.Num
			}
			composite := len(r.Children) > 0
			expanded := composite && in.expanded[path]
			out = append(out, visRow{
				row: r, path: path, depth: depth,
				composite: composite, expanded: expanded,
			})
			if expanded {
				walk(r.Children, depth+1, path)
			}
		}
	}
	walk(in.state.Fields, 0, "")

	return out
}

// rowCount is the fields-view row count: the Describe lines when root
// provided them (the fields tab is the Describe output), else the
// flattened tree rows.
func (in *Inspector) rowCount() int {
	if n := len(in.state.DescribeText); n > 0 {
		return n
	}

	return len(in.visibleRows())
}

// rowAt returns the visible row under index i (ok=false when the view
// is empty, the Describe output owns the pane, or i is out of range).
func (in *Inspector) rowAt(i int) (visRow, bool) {
	if len(in.state.DescribeText) > 0 {
		return visRow{}, false
	}
	rows := in.visibleRows()
	if i < 0 || i >= len(rows) {
		return visRow{}, false
	}

	return rows[i], true
}

// moveCursor advances the cursor and clamps it into the visible rows.
func (in *Inspector) moveCursor(delta int) {
	in.cursor = min(max(in.cursor+delta, 0), max(in.rowCount()-1, 0))
	in.clampTop()
}

// clampTop keeps the scroll window covering the cursor (fields view).
func (in *Inspector) clampTop() {
	if h := in.fieldsHeight(); h > 0 {
		if in.cursor < in.top {
			in.top = in.cursor
		}
		if in.cursor >= in.top+h {
			in.top = in.cursor - h + 1
		}
	}
}

// toggleAtCursor expands (dir>0) or collapses (dir<0) the composite under
// the cursor; non-composite rows are untouched.
func (in *Inspector) toggleAtCursor(expand bool) {
	vr, ok := in.rowAt(in.cursor)
	if !ok || !vr.composite || in.expanded[vr.path] == expand {
		return
	}
	if expand {
		in.expanded[vr.path] = true
	} else {
		delete(in.expanded, vr.path)
	}
	in.clampCursor()
}

// enterAtCursor is Enter's dispatch: expand/collapse a composite, else
// yield the compose message for the inspected transaction (root treats
// it as a logged no-op; nil when nothing is inspected).
func (in *Inspector) enterAtCursor() tea.Cmd {
	if vr, ok := in.rowAt(in.cursor); ok && vr.composite {
		in.toggleAtCursor(!vr.expanded)

		return nil
	}
	if in.state.TxID == "" {
		return nil
	}
	id := in.state.TxID

	return func() tea.Msg { return TxComposeMsg{ID: id} }
}

// poolValue resolves the display value for row r: auto rows with a pool
// show pool[poolIdx % len] (the page only advances an index — the pool
// was pre-generated by root at state-build time); everything else shows
// Display.
func (in *Inspector) poolValue(r FieldRow) string {
	if r.Auto && len(r.AutoPreviews) > 0 {
		return r.AutoPreviews[in.poolIdx%len(r.AutoPreviews)]
	}

	return r.Display
}

// displayCell is the value cell text for r, mask-glyph-substituted per
// theme (the raw PAN never reaches the page; only the • glyph does).
func (in *Inspector) displayCell(r FieldRow) string {
	v := in.poolValue(r)
	if r.Masked && !in.th.ASCII {
		return v
	}

	return strings.ReplaceAll(v, "•", "*")
}

// bitNums returns the message-bit numbers set by the top-level fields
// (MTI/field 0 is not a bit; bit 1 marks the bitmap extension and is set
// implicitly when any field numbers 65..128 are present). Pure string
// logic over Fields[].Num — no ISO library in the page.
func (in *Inspector) bitNums() map[int]bool {
	set := map[int]bool{}
	extended := false
	for _, f := range in.state.Fields {
		n, err := strconv.Atoi(strings.TrimSpace(f.Num))
		if err != nil || n < 1 {
			continue
		}
		if n > 64 {
			extended = true
			if n <= 128 {
				set[n] = true
			}

			continue
		}
		set[n] = true
	}
	if extended {
		set[1] = true
	}

	return set
}
