package pages

import (
	key "charm.land/bubbles/v2/key"
	tea "charm.land/bubbletea/v2"

	"jiso/internal/tui/frame"
	"jiso/internal/tui/geom"
	"jiso/internal/tui/theme"
)

// Inspector is the §C message inspector: the fields tree (interpolated
// values, auto-preview pool, composite expansion), the packed-hex pane,
// a bitmap bit grid, and the raw inspect-JSON view, switched by the
// [fields] [bitmap] [packed] [raw json] tabs. Like Transactions it is a
// reference type: the router keeps one canonical instance in its
// registry, so tab/cursor/tree state survives page jumps. All app data
// arrives via SetState from the root model — the page never touches
// internal/app and never reads the clock (the contract).
//
// The page owns only page-local interaction state: the tab cycle index
// (unknown tabs are impossible), the tree cursor/scroll, the expand set
// (keyed by field path), the auto-preview pool index (`r` advances it —
// values were pre-generated by root), and the hex grouping toggle.
type Inspector struct {
	th    *theme.Theme
	state InspectorState

	nav inspNav

	tab     int // viewFields..viewRawJSON, cyclic
	cursor  int // fields-view row under the selector
	top     int // fields-view scroll offset
	poolIdx int // auto-preview pool cursor (r)

	expanded map[string]bool // field path → expanded (composites)

	width, height int // last tea.WindowSizeMsg (terminal, not content area)

	// sections records the geom.Rect of every widgets.Section this
	// page drew during the last render, in draw order and with a
	// content-relative origin (the hit-map finalises the
	// absolute offsets into the frame chrome).
	sections []geom.Rect
}

// inspNav is the §C keymap: tab/shift+Tab arrive as PaneFocusMsg from
// the router, so the page binds only its local keys.
type inspNav struct {
	Cancel key.Binding // esc: yield InspectorPopMsg
	Enter  key.Binding // expand composite, else yield TxComposeMsg
	Right  key.Binding // expand composite
	Left   key.Binding // collapse composite
	Down   key.Binding
	Up     key.Binding
	Pool   key.Binding // r: cycle auto-preview pool

	help []HelpEntry // §M registry, built from the bindings above
}

func newInspNav() inspNav {
	nav := inspNav{
		Cancel: key.NewBinding(key.WithKeys(theme.KeyEsc)),
		Enter:  key.NewBinding(key.WithKeys(theme.KeyEnter)),
		Right:  key.NewBinding(key.WithKeys("right")),
		Left:   key.NewBinding(key.WithKeys("left")),
		Down:   key.NewBinding(key.WithKeys("down", "j")),
		Up:     key.NewBinding(key.WithKeys("up", "k")),
		Pool:   key.NewBinding(key.WithKeys("r")),
	}
	nav.help = []HelpEntry{
		navEntry("move", nav.Up, nav.Down),
		actEntry("expand / compose", nav.Enter),
		actEntry("collapse", nav.Left),
		actEntry("expand", nav.Right),
		actEntry("cycle pool", nav.Pool),
		actEntry("back", nav.Cancel),
	}

	return nav
}

// NewInspector builds the page. A nil theme selects theme.Default
// (production); golden tests inject an explicit NewWith profile.
func NewInspector(th *theme.Theme) *Inspector {
	if th == nil {
		th = theme.Default()
	}

	return &Inspector{th: th, nav: newInspNav(), expanded: map[string]bool{}}
}

// ID reports the router slot this page fills ("scenario", the §C
// wire-compat slot name; see InspectorPageID).
func (in *Inspector) ID() string { return InspectorPageID }

// Theme exposes the resolved theme (view helpers and tests).
func (in *Inspector) Theme() *theme.Theme { return in.th }

// Size reports the last terminal size seen via WindowSizeMsg.
func (in *Inspector) Size() (width, height int) { return in.width, in.height }

// Tab reports the current view-tab index (tests).
func (in *Inspector) Tab() int { return in.tab }

// Cursor reports the fields-view cursor (tests).
func (in *Inspector) Cursor() int { return in.cursor }

// PoolIndex reports the auto-preview pool index (tests).
func (in *Inspector) PoolIndex() int { return in.poolIdx }

// HexWide reports the packed-pane grouping (tests).

// IsExpanded reports whether the composite at path is expanded (tests).
func (in *Inspector) IsExpanded(path string) bool { return in.expanded[path] }

// SetState replaces the rendered snapshot (root pushes it when it opens
// the inspector and on every recomposition request). Page-local
// interaction state survives: cursor is clamped into the new tree, the
// tab/expand/pool/hex settings stay.
func (in *Inspector) SetState(state InspectorState) {
	in.state = state
	in.clampCursor()
}

// clampCursor keeps the cursor (and the scroll window) inside the
// visible rows of the current tree (visible rows are recomputed lazily
// by the view).
func (in *Inspector) clampCursor() {
	in.cursor = min(max(in.cursor, 0), max(in.rowCount()-1, 0))
	in.clampTop()
}

// Update routes sizes, the router's pane-focus tabs, and keys; bus
// events are ignored with a nil command.
func (in *Inspector) Update(msg tea.Msg) (Page, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		in.width, in.height = msg.Width, msg.Height
	case PaneFocusMsg:
		in.cycleTab(msg.Reverse)
	case tea.KeyPressMsg:
		return in.updateKey(msg)
	}

	return in, nil
}

// cycleTab advances the view-tab index; modulo keeps it always valid.
func (in *Inspector) cycleTab(reverse bool) {
	step := 1
	if reverse {
		step = ViewTabCount - 1
	}
	in.tab = (in.tab + step) % ViewTabCount
}

// updateKey is the page-local keymap.
func (in *Inspector) updateKey(msg tea.KeyPressMsg) (Page, tea.Cmd) {
	switch {
	case key.Matches(msg, in.nav.Cancel):
		return in, func() tea.Msg { return InspectorPopMsg{} }
	case key.Matches(msg, in.nav.Pool):
		in.poolIdx++
		return in, nil
	case key.Matches(msg, in.nav.Down):
		in.moveCursor(1)
		return in, nil
	case key.Matches(msg, in.nav.Up):
		in.moveCursor(-1)
		return in, nil
	case key.Matches(msg, in.nav.Right):
		in.toggleAtCursor(true)
		return in, nil
	case key.Matches(msg, in.nav.Left):
		in.toggleAtCursor(false)
		return in, nil
	case key.Matches(msg, in.nav.Enter):
		return in, in.enterAtCursor()
	default:
		return in, nil
	}
}

// Hints is the §C context keymap; tab/compose/back are primary so the
// narrow footer keeps them (the router appends the global bindings).
func (in *Inspector) Hints() []frame.KeyHint {
	return []frame.KeyHint{
		{Key: theme.KeyTab, Desc: "views", Primary: true},
		{Key: theme.KeyEnter, Desc: "compose", Primary: true},
		{Key: theme.KeyEsc, Desc: "back", Primary: true},
		{Key: theme.KeyNavJK, Desc: hintScroll},
		{Key: "r", Desc: hintPreview},
	}
}
